artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/aditya345-coder/Datasets/raw/main/Datasets/WineQT.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/WineQT.csv
  STATUS_FILE: artifacts/data_validation/status.txt  
  # When it will do validation of the data
  # if the data is in correct format it will return status as true otherwise false
  # and if the status is false then pipeline will not start.



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/WineQT.csv



model_trainer:
  root_dir: artifacts/model_trainer
  X_train_data_path: artifacts/data_transformation/X_train.csv
  y_train_data_path: artifacts/data_transformation/y_train.csv
  X_test_data_path: artifacts/data_transformation/X_test.csv
  y_test_data_path: artifacts/data_transformation/y_test.csv

  model_name: model.joblib
  scaler_name: scaler.pkl



model_evaluation:
  root_dir: artifacts/model_evaluation
  X_test_data_path: artifacts/model_trainer/X_test_processed.csv
  y_test_data_path: artifacts/model_trainer/y_test.csv
  model_path: artifacts/model_trainer/model.joblib
  scaler_path: artifacts/model_trainer/scaler.pkl
  metric_file_name: artifacts/model_evaluation/metrics.json






